### ISSUE TITLE
Callback problem (str_replace)

### ISSUE THREAD

**Issue by czubu** [nelkasovic/laravel-full-calendar#4]
Hello.

I have issue with setting callbacks: `explode() expects parameter 1 to be string, array given`
I've debugged that causer is method `replaceCallbackPlaceholders()` (more precisely `Str::replaceArray()`) in Calendar class.
Can you fix this, or tell me how to call callbacks?

Thanks!

**Comment by amousavii** [comment]
I have the same problem on laravel 7 , any advice?

**Comment by zebamba** [comment]
@czubu 
Str::replaceArray first argument expected is a string the code passing an array of strings.

I am sure this works.

```

protected function replaceCallbackPlaceholders($json, $placeholders)
{
    foreach ($placeholders as $name => $placeholder) {
            $search = '"' . $placeholder . '"';
            $json = Str::replaceArray($search, [$this->getCallbacks()[$name]], $json);
        }

    return $json;
}
```

**Comment by emp-sean** [comment]
Can confirm that resolves the issue.

Can this please be merged in.
